### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by greyfiles** [greyfiles/CSC510-Projects#4]
Improve the Readme on the landing page of the repository to better the repository's initial impression on prospective users and contributors. The readme needs to both clearly and quickly explain the tool and it's features while at the same time being persuasive enough to "sell" the tool.

**Comment by JacobBow** [comment]
- Condensed README to be more concise and to the point
- Broke off some of the larger sections into separate .md files
- Add references for VMs for Windows users
- Updates can be found here: https://github.com/greyfiles/GITS/commits?author=JacobBow
